<a href="https://colab.research.google.com/github/2303A51259/AIML/blob/main/Lab1_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy
a=int(input("Enter no.of elements in list:"))
list=[]
n=a
while(n>0):
  b=int(input("Enter element:"))
  list.append(b)
  n=n-1
print(list)
arr=numpy.array([1,2,3])
ar2=numpy.array([2,4,6])
print("First element: ",arr[0])
print("Type:",type(arr))
print("Type:",type(list))
print("Multiplication:",arr*ar2)
print("Division:",arr/ar2)
print("Exponential:",arr**ar2)
print("Addition of Two:",arr+ar2)
p=numpy.sin(arr)
s=numpy.log(arr)
q=numpy.log2(ar2)
r=numpy.exp(arr)
print(p)
print(s)
print(q)
print(r)

Enter no.of elements in list:1
Enter element:1
[1]
First element:  1
Type: <class 'numpy.ndarray'>
Type: <class 'list'>
Multiplication: [ 2  8 18]
Division: [0.5 0.5 0.5]
Exponential: [  1  16 729]
Addition of Two: [3 6 9]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]
[1.        2.        2.5849625]
[ 2.71828183  7.3890561  20.08553692]
